version: '3'

services:
  ardupilot_ros:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=ros
        - USER_UID=1000
        - USER_GID=1000
    container_name: ardupilot_ros
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/ros/.Xauthority
      - ./src:/tmp/local_src  # Mount your local src to a temporary directory
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /home/ros/ros2_ws/src
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    # Copy files at startup if they don't exist yet
    command: bash -c "if [ ! -f /home/ros/ros2_ws/src/.copied ]; then cp -r /tmp/local_src/* /home/ros/ros2_ws/src/ && touch /home/ros/ros2_ws/src/.copied; fi && bash"